name: yutipy
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - python-dotenv==1.0.1
    - rapidfuzz==3.12.1
    - requests==2.32.3
    - ytmusicapi==1.10.1
    - pytest==8.3.4
